version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: mongo
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/mongo --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - "6000:6000"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - PORT=6000
      - MONGO_URI=mongodb://mongo:27017/mongo
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=production
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/app
     
      - /app/node_modules
    networks:
      - app-network

volumes:
  mongo-data:
  backend-node-modules:
  frontend-node-modules:

networks:
  app-network:
    driver: bridge
